---
image:
  file: '.gitpod.Dockerfile'

vscode:
  extensions:
    - 'ms-python.python'
    - 'tabnine.tabnine-vscode'
    - 'fileicons.file-icons'
    - 'ms-azuretools.vscode-docker'
    - 'file-icons.file-icons'
    - 'itsjonq.owlet'
    - 'bungcip.better-toml'
    - 'eamodio.gitlens'
    - 'ms-toolsai.jupyter'
    - 'ms-toolsai.jupyter-keymap'
    - 'ms-toolsai.jupyter-renderers'
    - 'ms-toolsai.vscode-jupyter-slideshow'
    - 'ms-toolsai.vscode-jupyter-cell-tags'
