---
repos:
  - repo: 'https://github.com/jorisroovers/gitlint'
    rev: 'v0.19.1'
    hooks:
      - id: 'gitlint'

  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: 'v0.0.260'
    hooks:
      - id: 'ruff'
