---
on:
  pull_request:
    branches:
      - 'main'
  push:

name: 'Lint commit messages'
jobs:
  gitlint:
    name: 'commit messages'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - name: 'Set up python 3.11'
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.11'

      - name: 'Test Commit Messages Lint'
        run: |
          pip install "hatch>=1.6.3,<2.0.0"
          hatch run git:lint --ignore-stdin
