---
on:
  pull_request:
    branches:
      - 'main'
  push:

name: 'Lint check'
jobs:
  ruff:
    name: 'ruff check'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.11'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - name: 'Set up python ${{ matrix.python-version }}'
        uses: 'actions/setup-python@v4'
        with:
          python-version: '${{ matrix.python-version }}'

      - name: 'Test Code Lint'
        run: |
          pip install "hatch>=1.6.3,<2.0.0"
          hatch run style:check
